const lessonTitle = "午后的故事";

const lessonData = [
    // 正文第 1 段
    ["一声", "yī shēng", "A sound of", "Satu bunyi"],
    ["尖啸刺耳的", "jiān xiào cì ěr de", "piercing and ear-splitting", "yang menjerit nyaring dan memekakkan telinga"],
    ["叫骂声", "jiào mà shēng", "scolding and cursing voice", "suara maki-hamun"],
    ["在大街上", "zài dà jiē shàng", "on the main street", "di jalan besar"],
    ["响起", "xiǎng qǐ", "rang out", "berbunyi"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles / like", "bagaikan / seperti"],
    ["平空", "píng kōng", "out of nowhere / out of thin air", "tiba-tiba dari langit"],
    ["炸起", "zhà qǐ", "exploded up", "meletus up"],
    ["一颗", "yì kē", "a (measure word for bomb/thunder)", "sebiji"],
    ["响雷", "xiǎng léi", "loud thunderclaps", "guruh yang kuat"],
    ["，", "", "", ""],
    ["撕破了", "sī pò le", "tore apart", "merobek / mengoyak"],
    ["大街的", "dà jiē de", "street's", "jalan besar punya"],
    ["宁静", "níng jìng", "tranquility / silence", "ketenteraman / kesunyian"],
    ["。", "", "", ""],
    ["当时是", "dāng shí shì", "At that time was", "Pada masa itu adalah"],
    ["午后", "wǔ hòu", "afternoon", "selepas tengah hari / petang"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["明亮亮的", "míng liàng liàng de", "bright and shining", "yang sangat terang-benderang"],
    ["，", "", "", ""],
    ["没有", "méi yǒu", "did not have", "tidak ada"],
    ["多少事", "duō shǎo shì", "much business / things", "banyak urusan"],
    ["要做的", "yào zuò de", "required to do's", "yang perlu dibuat punya"],
    ["人们", "rén men", "people", "orang ramai"],
    ["三五成堆", "sān wǔ chéng duī", "in groups of threes and fives", "berkumpul bertumpu-tumpu kecil"],
    ["聚在", "jù zài", "gathered at", "berhimpun di"],
    ["大街两旁", "dài jiē liǎng páng", "both sides of the street", "kedua-dua belah kaki jalan"],
    ["闲谈", "xián tán", "chatting / gossiping", "berbual-bual kosong / bersembang"],
    ["和", "hé", "and", "dan"],
    ["下围棋", "xià wéi qí", "playing Go (chess game)", "bermain catur Go"],
    ["，", "", "", ""],
    ["街道上", "jiē dào shàng", "on the streets", "di atas jalan raya"],
    ["有", "yǒu", "had", "ada"],
    ["流水一样的", "liú shuǐ yí yàng de", "flowing water-like", "bagaikan air mengalir punya"],
    ["行人", "xíng rén", "pedestrians", "pejalan kaki"],
    ["。", "", "", ""],
    ["听到", "tīng dào", "Hearing", "Apabila mendengar"],
    ["这一声", "zhè yī shēng", "this sound of", "bunyi satu ini punya"],
    ["叫骂", "jiào mà", "scolding", "maki-hamun"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["不约而同地", "bù yuē ér tóng de", "coincidentally / happen to do the same", "secara spontan bersama / serentak"],
    ["伸长", "shēn cháng", "stretched long", "memanjangkan / menghulur"],
    ["脖子", "bó zi", "necks", "leher"],
    ["，", "", "", ""],
    ["睁圆", "zhēng yuán", "stared round / opened wide", "membeliakkan / membuka luas"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["朝", "cháo", "towards", "menghala ke arah"],
    ["叫骂的", "jiào mà de", "cursing's", "tempat maki-hamun punya"],
    ["地方", "dì fāng", "place", "kawasan / tempat"],
    ["望去", "wàng qù", "gazed over", "melihat pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段
    ["只见", "zhǐ jiàn", "Only to see", "Hanya kelihatan"],
    ["一个", "yí gè", "a", "seorang"],
    ["壮汉", "zhuàng hàn", "burly man / robust fellow", "lelaki sasa / orang kuat"],
    ["手持", "shǒu chí", "holding in hand", "memegang di tangan"],
    ["一把", "yì bǎ", "a (measure word for knife)", "sebilah"],
    ["锋利的", "fēng lì de", "sharp", "pisau yang sangat tajam punya"],
    ["菜刀", "cài dǎo", "cleaver / kitchen knife", "pisau pemotong daging / pisau dapur"],
    ["在大街上", "zài dà jiē shàng", "on the street", "di jalan besar"],
    ["狂奔", "kuáng bēn", "galloping / running wildly", "berlari meluru dengan liar / berkejaran"],
    ["，", "", "", ""],
    ["他满脸", "tā mǎn liǎn", "his whole face", "seluruh mukanya sarat dipenuhi"],
    ["杀气", "shā qì", "murderous look", "aura membunuh / wajah bengis"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while on one hand", "sambil"],
    ["狂奔", "kuáng bēn", "running wildly", "berlari kencang"],
    ["一边", "yì biān", "while on the other hand", "sambil"],
    ["叫骂", "jiào mà", "scolding / cursing", "memaki-hamun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu punya"],
    ["手中的", "shǒu zhōng de", "inside hand's", "dalam tangan punya"],
    ["菜刀", "cài dāo", "cleaver", "pisau pemotong daging"],
    ["在", "zài", "under / in", "di bawah"],
    ["明亮亮的", "míng liàng liàng de", "bright", "terang-benderang punya"],
    ["阳光下", "yáng guāng xià", "sunlight underneath", "cahaya matahari"],
    ["发出", "fā chū", "emitted", "mengeluarkan"],
    ["耀眼的", "yào yǎn de", "dazzling / glaring", "kilauan yang menyilaukan mata"],
    ["光芒", "guāng máng", "rays / light", "sinaran cahaya"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles", "bagaikan / seperti"],
    ["一道", "yí dào", "a ray of / a line of", "sejalur"],
    ["火绳", "huǒ shéng", "fire rope / fuse", "tali api"],
    ["烧灼着", "shāo zhuó zhe", "scorching / searing", "membakar hangus"],
    ["人们的", "rén men de", "people's", "orang ramai punya"],
    ["眼帘", "yǎn lián", "eyesight / eyes", "pandangan mata"],
    ["。", "", "", ""],
    ["大街的", "dài jiē de", "street's", "Jalan besar punya"],
    ["行人", "xíng rén", "pedestrians", "pejalan kaki"],
    ["纷纷", "fēn fēn", "one after another", "bertumpu-tumpu / ramai-ramai"],
    ["停了下来", "tíng le xià lái", "stopped down", "berhenti belaka"],
    ["，", "", "", ""],
    ["像", "xiàng", "as if", "seolah-olah bagaikan"],
    ["被谁", "bèi shéi", "by whom", "diarahkan oleh sesiapa"],
    ["无声", "wú shēng", "silently", "tanpa sebarang suara"],
    ["指挥着", "zhǐ huī zhe", "directed / commanded", "sedang dipimpin / dikomandokan"],
    ["似的", "shì de", "resembling", "sedemikian"],
    ["一同", "yī tóng", "together", "serentak bersama"],
    ["往", "wǎng", "towards", "menghala ke arah"],
    ["街道两旁", "jiē dào liǎng páng", "both sides of the street", "kedua-dua belah kaki jalan"],
    ["挤靠", "jǐ kào", "crowded and leaned", "bersesak-sesak merapat"],
    ["。", "", "", ""],
    ["街道两旁的", "jiē dào liǎng páng de", "on both sides of the street's", "Kedua-dua belah kaki jalan punya"],
    ["男男女女", "nán nán nǚ nǚ", "men and women", "lelaki dan perempuan"],
    ["也都", "yě dōu", "all also", "pun semuanya"],
    ["站起来", "zhàn qǐ shēn lái", "stood up body", "bangun berdiri"],
    ["，", "", "", ""],
    ["紧张地", "jǐn zhāng de", "nervously / anxiously", "dengan penuh cemas / tegang"],
    ["往", "wǎng", "towards", "menghala ke arah"],
    ["更里面的", "gèng lǐ miàn de", "further inside's", "bahagian yang lebih dalam lagi punya"],
    ["地方", "dì fāng", "place", "kawasan / tempat"],
    ["挤靠", "jǐ kào", "crowded and leaned", "bersesak merapat"],
    ["。", "", "", ""],
    ["一时间", "yī shí jiān", "For a moment / instantly", "Dalam sekelip mata"],
    ["街道两旁", "jiē dào liǎng páng", "both sides of the street", "kedua-dua belah kaki jalan"],
    ["形成", "xíng chéng", "formed", "membentuk"],
    ["两堵", "liǎng dǔ", "two blocks of (measure word for walls)", "dua buah"],
    ["人墙", "rén qiáng", "human walls", "dinding manusia"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semuanya"],
    ["屏住呼吸", "bǐng zhù hū xī", "held breath", "menahan nafas"],
    ["，", "", "", ""],
    ["不敢", "bù gǎn", "dare not", "tidak berani"],
    ["多说", "duō shuō", "say more", "bercakap lebih / banyak cakap"],
    ["半句话", "bàn jù huà", "half a sentence", "sepatah perkataan pun"],
    ["，", "", "", ""],
    ["茫然地", "máng rán de", "blankly / vacantly / blankly", "dengan pandangan kosong / kebingungan"],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["大街上", "dài jiē shàng", "on the street", "di jalan besar"],
    ["那个", "nà gè", "that", "orang sasa yang itu"],
    ["狂奔的", "kuáng bēn de", "running wildly's", "sedang berlari meluru punya"],
    ["壮汉", "zhuàng hàn", "burly man", "lelaki sasa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["还在", "hái zài", "still currently", "masih sedang"],
    ["叫骂", "jiào mà", "scolding", "memaki-hamun"],
    ["，", "", "", ""],
    ["狂奔", "kuáng bēn", "running wildly", "berlari meluru"],
    ["。", "", "", ""],
    ["大街上", "dài jiē shàng", "On the street", "Di atas jalan besar"],
    ["空荡荡的", "kōng dàng dàng de", "empty / deserted", "sunyi sepi / kosong melongpong"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah bagaikan"],
    ["静止的", "jìng zhǐ de", "still / static", "air yang pegun / tenang tidak bergerak punya"],
    ["流水", "liú shuǐ", "flowing water", "aliran air"],
    ["。", "", "", ""],
    ["在", "zài", "In / at", "Pada waktu"],
    ["午后", "wǔ hòu", "afternoon", "petang"],
    ["，", "", "", ""],
    ["整个", "zhěng gè", "the whole", "seluruh"],
    ["大街上", "dài jiē shàng", "on the street", "jalan besar atas"],
    ["只有", "zhǐ yǒu", "only had", "hanya ada seorang"],
    ["一个", "yí gè", "one", "sahaja"],
    ["壮汉", "zhuàng hàn", "burly man", "lelaki sasa"],
    ["在", "zài", "doing (aspect marker)", "sedang"],
    ["狂奔", "kuáng bēn", "running wildly", "berlari meluru"],
    ["，", "", "", ""],
    ["在", "zài", "doing", "sedang"],
    ["叫骂", "jiào mà", "scolding", "memaki-hamun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["“", "", "", ""],
    ["站住", "zhàn zhù", "Stop / halt", "Berhenti"],
    ["！", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife / blade", "pisau itu"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["突然", "tū rán", "Suddenly", "Tiba-tiba"],
    ["，", "", "", ""],
    ["又一声", "yòu yì shēng", "another sound of / another strike of", "satu lagi bunyi"],
    ["炸雷", "zhà léi", "thunderstrike", "letusan guruh"],
    ["在大街上", "zài dà jiē shàng", "on the street", "di jalan besar"],
    ["炸响", "zhà xiǎng", "exploded loudly", "meletus kuat berbunyi"],
    ["，", "", "", ""],
    ["震得", "zhèn de", "shook until", "menggegar sehingga menyebabkan"],
    ["两旁的", "liǎng páng de", "both sides'", "kedua-dua belah punya"],
    ["人墙", "rén qiáng", "human walls", "dinding manusia"],
    ["悸动了", "jì dòng le", "trembled / shuddered once", "terperanjat geger seketika"],
    ["一下", "yí xià", "briefly", "sekejap"],
    ["，", "", "", ""],
    ["人墙上的", "rén qiáng shàng de", "on the human walls'", "di atas dinding manusia punya"],
    ["一双双", "yì shuāng shuāng", "pairs of", "setiap pasang"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["齐刷刷地", "qí shuā shuā de", "uniformly / all together", "serentak bersama-sama belaka"],
    ["循声望去", "xún shēng wàng qù", "followed the sound to look over", "mencari arah bunyi melihat pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["一个", "yí gè", "A / one", "Seorang"],
    ["老人", "lǎo rén", "old man", "orang tua"],
    ["站立在", "zhàn lì zài", "standing at", "berdiri tegak di tengah-tengah"],
    ["大街中央", "dài jiē zhōng yāng", "center of the street", "jalan besar"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles / like", "bagaikan / seperti"],
    ["巍然挺立的", "wēi rán tǐng lì de", "towering and standing upright", "sebatang pokok yang berdiri megah gagah"],
    ["一棵松", "yì kē sōng", "a pine tree", "pohon pain"],
    ["，", "", "", ""],
    ["迎面", "yíng miàn", "head-on / face to face", "berhadapan muka / berdepan"],
    ["拦住", "lán zhù", "blocked / stopped", "menghalang sekat"],
    ["狂奔", "kuáng bēn", "running wildly", "berlari meluru"],
    ["叫骂的", "jiào mà de", "cursing's", "maki-hamun punya"],
    ["壮汉", "zhuàng hàn", "burly man", "lelaki sasa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah bagaikan"],
    ["没有听见", "méi yǒu tīng jiàn", "did not hear", "langsung tidak mendengar"],
    ["老人的", "lǎo rén de", "old man's", "orang tua punya"],
    ["喊声", "hǎn shēng", "shouting", "laungan suara"],
    ["，", "", "", ""],
    ["仍然", "réng rán", "still", "tetap masih"],
    ["挥舞着", "huī wǔ zhe", "waving / brandishing", "mengacung-ngacungkan"],
    ["菜刀", "cài dāo", "cleaver", "pisau pemotong daging"],
    ["往前", "wǎng qián", "forward", "menghala ke depan"],
    ["狂奔", "kuáng bēn", "running wildly", "berlari meluru"],
    ["，", "", "", ""],
    ["他手中的", "tā shǒu zhōng de", "inside his hand's", "dalam tangan dia punya"],
    ["菜刀", "cài dāo", "cleaver", "pisau dapur"],
    ["闪着", "shǎn zhe", "flashing / gleaming", "berkilat-kilat"],
    ["亮光", "liàng guāng", "bright light", "sinaran kilau"],
    ["，", "", "", ""],
    ["犹如", "yóu rú", "just like", "bagaikan / mirip semestinya"],
    ["一条", "yì tiáo", "one (measure word for snake)", "seekor"],
    ["吐着", "tǔ zhe", "spitting / flicking (tongue)", "sedang menjelirkan"],
    ["毒芯的", "dú xīn de", "poisonous tongue / core", "lidah berbisa punya"],
    ["长蛇", "cháng shé", "long snake", "ular panjang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["“", "", "", ""],
    ["站住", "zhàn zhù", "Stop", "Berhenti"],
    ["！", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife", "pisau itu"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["又", "yòu", "again", "sekali lagi"],
    ["大吼一声", "dà hǒu yì shēng", "roared loudly once", "melaung dengan tersangat kuat"],
    ["，", "", "", ""],
    ["声若洪钟", "shēng ruò hóng zhōng", "voice like a huge bell", "suara bagaikan gendering besar / lantang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["这次", "zhè cì", "this time", "kali ini"],
    ["听到了", "tīng dào le", "heard it", "telah mendengarnya"],
    ["，", "", "", ""],
    ["他一愣怔", "tā yí lèng zhèng", "he was dazed for a moment / stunned", "dia tertegun seketika"],
    ["停了", "tíng le", "stopped", "berhenti"],
    ["下来", "xià lái", "down", "semula"],
    ["，", "", "", ""],
    ["狐疑地", "hú yí de", "suspiciously / doubtfully", "dengan penuh rasa curiga / waswas"],
    ["瞅一眼", "chǒu yì yǎn", "glanced once at", "menjeling sekilas pandang kepada"],
    ["老人", "lǎo rén", "old man", "orang tua itu"],
    ["。", "", "", ""],
    ["但", "dàn", "But", "Namun"],
    ["很快", "hěn kuài", "very quickly", "dengan sangat cepat"],
    ["壮汉", "zhuàng hàn", "burly man", "lelaki sasa itu"],
    ["又", "yòu", "again", "pula kembali"],
    ["凶相毕露", "xiōng xiàng bì lù", "ferocious features completely revealed / showed claws", "menunjukkan wajah bengisnya yang asal belaka"],
    ["，", "", "", ""],
    ["狂嚣", "kuáng xiāo", "clamored wildly / clamored arrogantly", "melaung angkuh / menjerit liar"],
    ["起来", "qǐ lái", "up", "mula"],
    ["，", "", "", ""],
    ["疯狂地", "fēng kuáng de", "疯狂地", "dengan gila-gilaan"],
    ["挥舞着", "huī wǔ zhe", "brandishing / waving", "mengayun-ngayunkan"],
    ["手中的", "shǒu zhōng de", "inside hand's", "dalam tangan punya"],
    ["菜刀", "cài dāo", "cleaver", "pisau dapur"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles", "bagaikan"],
    ["空中", "kōng zhōng", "in the air", "di udara"],
    ["无数条", "wú shù tiáo", "countless lines of (snakes)", "berpuluh-puluh ekor"],
    ["毒蛇", "dú shé", "poisonous snakes", "ular berbisa"],
    ["在", "zài", "doing (aspect marker)", "sedang"],
    ["吐芯", "tǔ xīn", "flicking tongues", "menjelirkan lidah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段
    ["“", "", "", ""],
    ["让开", "ràng kāi", "Step aside / move out of the way", "Tepi / ke tepi"],
    ["！", "", "", ""],
    ["我要", "wǒ yào", "I want to", "Saya mahu"],
    ["杀林三", "shā lín sān", "kill Lin San (Name)", "membunuh Lin San"],
    ["，", "", "", ""],
    ["不关你的事", "bù guān nǐ de shì", "none of your business", "tidak ada kena-mengena dengan urusan kamu"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["岿然不动", "kuī rán bú dòng", "stood firm and immovable / steadfast", "tetap tegak berdiri tanpa berganjak sedikit pun"],
    ["，", "", "", ""],
    ["威严地", "wēi yán de", "majestically / authoritatively", "dengan penuh tegas / berwibawa mulia"],
    ["吼道", "hǒu dào", "roared / bellowed", "melaung kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife", "pisau itu"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["声嘶力竭地", "shēng sī lì jié de", "shouted himself hoarse / exhaustedly screaming", "menjerit dengan sehabis-habis suara / serak suara"],
    ["叫道", "jiào dào", "shouted", "melaung pekik"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你让开", "nǐ ràng kāi", "You step aside", "Kamu ke tepi lah"],
    ["！", "", "", ""],
    ["不让开", "bú ràng kāi", "If you don't step aside", "jika tidak ke tepi"],
    ["我就", "wǒ jiù", "I then", "saya terus"],
    ["先杀了你", "xiān shā le nǐ", "kill you first", "akan membunuh kamu dahulu"],
    ["，", "", "", ""],
    ["再去", "zài qù", "then go to", "kemudian baru pergi"],
    ["杀林三", "shā lín sān", "kill Lin San", "membunuh Lin San"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife", "pisau itu"],
    ["！", "", "", ""],
    ["我不会", "wǒ bú huì", "I will not", "Saya tidak akan"],
    ["让你", "ràng nǐ", "let you", "membiarkan kamu"],
    ["走过去", "zǒu guò qù", "walk over / pass by", "melangkah melintasi pergi"],
    ["，", "", "", ""],
    ["除非", "chú fēi", "unless", "melainkan sekiranya"],
    ["我倒下", "wǒ dǎo xià", "I fall down", "saya rebah tumbang"],
    ["。", "", "", ""],
    ["你听着", "nǐ tīng zhe", "You listen closely", "Kamu dengar baik-baik"],
    ["，", "", "", ""],
    ["要是死", "yào shì sǐ", "if it comes to death", "sekiranya menemui ajal death"],
    ["，", "", "", ""],
    ["我已经", "wǒ yǐ jīng", "I already", "saya sudah pun"],
    ["死过三次了", "sǐ guò sān cì le", "died three times", "pernah mati sebanyak tiga kali dah"],
    ["。", "", "", ""],
    ["敌人的", "dí rén de", "Enemy's", "Musuh punya"],
    ["子弹", "zǐ dàn", "bullet", "peluru"],
    ["从我", "cóng wǒ", "from my", "dari arah saya punya"],
    ["前胸", "qián xiōng", "front chest", "dada depan"],
    ["穿过", "chuān guò", "pierced through", "menembusi menuju ke"],
    ["后背", "hòu bèi", "back", "belakang badan"],
    ["钻出", "zuān chū", "drilled out / exited", "terkeluar keluar"],
    ["，", "", "", ""],
    ["我没有死", "wǒ méi yǒu sǐ", "I did not die", "saya tidak mati"],
    ["；", "", "", ""],
    ["一辆", "yí liàng", "a (measure word for lorry)", "sebuah"],
    ["货车", "huò chē", "truck / lorry", "lori barang / trak"],
    ["把我", "bǎ wǒ", "object particle (me)", "menyebabkan saya"],
    ["撞得飞起", "zhuàng de fēi qǐ", "knocked flying up", "dilanggar melambung tinggi up"],
    ["，", "", "", ""],
    ["在医院", "zài yī yuàn", "in hospital", "di dalam hospital"],
    ["昏迷了", "hūn mí le", "comatose / unconscious", "koma / tidak sedarkan diri"],
    ["三天", "sān tiān", "three days", "selama tiga hari"],
    ["，", "", "", ""],
    ["我也没有死", "wǒ yě méi yǒu sǐ", "I also did not die", "saya pun tetap tidak mati"],
    ["；", "", "", ""],
    ["歹徒的", "dǎi tú de", "thug's / gangster's", "penjenayah punya"],
    ["刀", "dāo", "knife", "pisau belati"],
    ["从我", "cóng wǒ", "from my", "dari arah saya punya"],
    ["胸前", "xiōng qián", "front chest", "depan dada"],
    ["刺进去", "cì jìn qù", "stabbed into", "ditikam masuk ke dalam"],
    ["，", "", "", ""],
    ["鲜血", "xiān xuè", "fresh blood", "darah merah pekat"],
    ["淌了一地", "tǎng le yí dì", "dripped a whole floor / flowed", "mengalir tumpah penuh lantai"],
    ["，", "", "", ""],
    ["我还是", "wǒ hái shì", "I still", "saya tetap juga"],
    ["没有死", "méi yǒu sǐ", "did not die", "tidak mati"],
    ["。", "", "", ""],
    ["这三次", "zhè sān cì", "These three times", "Ketiga-tiga kali ini"],
    ["我", "wǒ", "I", "saya"],
    ["都没有死", "dōu méi yǒu sǐ", "all did not die", "langsung semuanya tidak mati"],
    ["，", "", "", ""],
    ["难道还怕", "nán dào hái pà", "could it be that I'm still afraid of (rhetorical)", "masakan saya masih takut lagi akan"],
    ["再有一次吗", "zài yǒu yí cì ma", "having one more time", "ada satu kali lagi kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 16 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["无望地", "wú wàng de", "hopelessly", "dengan nada penuh putus asa berkata"],
    ["说", "shuō", "said", "perkataan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不", "bù", "No", "Jangan / tidak"],
    ["，", "", "", ""],
    ["你让开", "nǐ ràng kāi", "you step aside", "kamu ke tepi lah"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 17 段
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife", "pisau itu"],
    ["！", "", "", ""],
    ["我是一个", "wǒ shì yí gè", "I am a", "Saya adalah seorang"],
    ["失去", "shī qù", "lost", "yang kehilangan"],
    ["儿子的", "ér zi de", "son's", "anak lelaki punya"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["，", "", "", ""],
    ["我不能", "wǒ bù néng", "I cannot", "saya tidak boleh membiarkan"],
    ["再让", "zài ràng", "again let", "sekali lagi menyebabkan"],
    ["一个", "yí gè", "a", "seorang lagi"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["失去", "shī qù", "lose", "kehilangan"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 18 段
    ["听到", "tīng dào", "Hearing", "Apabila mendengar"],
    ["老人", "lǎo rén", "old man's", "orang tua punya"],
    ["这句", "zhè jù", "this sentence of", "sebaris ayat yang"],
    ["悲凉的", "bēi liáng de", "desolate / sorrowful", "tersangat hiba dan pilu punya"],
    ["话语", "huà yǔ", "words", "kata-kata"],
    ["，", "", "", ""],
    ["街道两旁", "jiē dào liǎng páng", "both sides of the street", "kedua-dua belah kaki jalan punya"],
    ["的人墙", "rén qiáng", "human walls", "dinding manusia"],
    ["又", "yòu", "again", "sekali lagi"],
    ["一阵", "yí zhèn", "a burst of (tremor)", "mengalami suatu"],
    ["悸动", "jì dòng", "shudder / tremor", "gegaran geger gementar"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles / like", "bagaikan"],
    ["一阵", "yí zhèn", "a burst of", "sehembus"],
    ["寒风", "hán fēng", "cold wind", "angin kencang yang sejuk"],
    ["贴着", "tiē zhe", "scraping against / brushing against", "merapat menyusuri"],
    ["人墙", "rén qiáng", "human walls", "dinding manusia itu"],
    ["刮过", "guā guò", "blew past", "berhembus lalu"],
    ["，", "", "", ""],
    ["人们的心", "rén men de xīn", "people's hearts", "hati orang ramai belaka"],
    ["都", "dōu", "all", "pun semuanya"],
    ["不住地", "bú zhù de", "ceaselessly / non-stop", "tidak henti-henti"],
    ["颤抖着", "chàn dǒu zhe", "shivering / trembling", "sedang gementar pilu"],
    ["。", "", "", ""],
    ["许多人", "xǔ duō rén", "Many people", "Ramai orang"],
    ["都", "dōu", "all", "sememangnya"],
    ["清楚地", "qīng chǔ de", "clearly", "dengan sangat jelas"],
    ["记得", "jì de", "remembered", "mengingati bahawa"],
    ["也是", "yě shì", "also was", "pun pada waktu yang"],
    ["这样一个", "zhè yàng yí gè", "such a", "sebegini punya"],
    ["午后", "wǔ hòu", "afternoon", "petang hari"],
    ["，", "", "", ""],
    ["也是", "yě shì", "also was", "pun dalam keadaan"],
    ["男男女女", "nán nán nǚ nǚ", "men and women", "lelaki dan perempuan"],
    ["三五成堆", "sān wǔ chéng duī", "in groups of threes and fives", "berkumpul bertumpu-tumpu kecil"],
    ["聚在", "jù zài", "gathered at", "berhimpun di"],
    ["大街两旁", "dài jiē liǎng páng", "both sides of the street", "kedua-dua belah kaki jalan"],
    ["下围棋", "xià wéi qí", "playing Go", "bermain catur Go"],
    ["，", "", "", ""],
    ["街道上", "jiē dào shàng", "on the street", "di atas jalan raya"],
    ["行人如流水", "xíng rén rú liú shuǐ", "pedestrians flowing like water", "pejalan kaki berduyung bagaikan air mengalir"],
    ["。", "", "", ""],
    ["三个", "sān gè", "Three", "Tiga orang"],
    ["歹徒", "dǎi tú", "thugs / gangsters", "penjenayah / penyangak"],
    ["在", "zài", "doing (aspect)", "sedang"],
    ["殴打", "ōu dǎ", "beating up / assaulting", "memukul / membelasah"],
    ["一个", "yí gè", "a", "seorang"],
    ["年轻人", "nián qīng rén", "young man", "pemuda"],
    ["，", "", "", ""],
    ["年轻人", "nián qīng rén", "the young man", "pemuda itu"],
    ["就是", "jiù shì", "exactly was", "sememangnya adalah"],
    ["老人的", "lǎo rén de", "old man's", "orang tua punya"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["。", "", "", ""],
    ["当时", "dāng shí", "At that time", "Pada waktu itu"],
    ["没有", "méi yǒu", "did not have / nobody", "langsung tidak ada seorang pun"],
    ["出来", "chū lái", "came out to", "tampil keluar untuk"],
    ["阻拦", "zǔ lán", "stop / intervene", "menghalang sekat"],
    ["，", "", "", ""],
    ["大街上", "dài jiē shàng", "on the street", "di atas jalan besar"],
    ["仿佛", "fǎng fú", "as if / looked like", "seolah-olah bagaikan"],
    ["空无一人", "kōng wú yī rén", "completely deserted / nobody there", "kosong melongpong tiada satu jiwa pun"],
    ["。", "", "", ""],
    ["老人的", "lǎo rén de", "old man's", "Orang tua punya"],
    ["儿子", "ér zi", "son", "anak lelaki itu"],
    ["被打倒", "bèi dǎ dǎo", "was beaten down", "telah dibelasah rebah"],
    ["在地", "zài dì", "on the ground", "di atas lantai tanah"],
    ["，", "", "", ""],
    ["肠子", "cháng zi", "intestines / guts", "tali perut / usus"],
    ["流出", "liú chū", "flowed out", "terburai keluar melimpah"],
    ["一堆", "yì duī", "a pile", "seonggok"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "sebuah"],
    ["鲜活的", "xiān huó de", "vibrant / fresh living", "nyawa yang segar bugar punya"],
    ["生命", "shēng mìng", "life", "riwayat hidup"],
    ["在", "zài", "in", "pada waktu"],
    ["午后", "wǔ hòu", "afternoon", "petang hari"],
    ["明亮亮的", "míng liàng liàng de", "bright", "terang-benderang punya"],
    ["阳光下", "yáng guāng xià", "sunlight underneath", "cahaya matahari di bawah"],
    ["，", "", "", ""],
    ["在", "zài", "under / in", "di hadapan"],
    ["众目睽睽之下", "zhòng mù kuí kuí zhī xià", "under the watchful eyes of all / public gaze", "pandangan mata orang ramai khalayak ramai belaka"],
    ["枯萎了", "kū wěi le", "withered / died away", "telah layu menemui ajal tumpah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 19 段
    ["“", "", "", ""],
    ["放下", "fàng xià", "Put down", "Letakkan bawah"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["刀", "dāo", "knife", "pisau itu"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["又", "yòu", "again", "sekali lagi"],
    ["高声吼道", "gāo shēng hǒu dào", "roared in high voice", "melaung kuat dengan nada tinggi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 20 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["无力地", "wú lì de", "feebly / weakly", "dengan tawar tenaga / lemah langsung"],
    ["哀号", "āi háo", "wailed / moaned piteously", "meratap hiba melaung"],
    ["一声", "yì shēng", "a sound of", "satu"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不——", "bù", "No--", "Jangan--"],
    ["”", "", "", ""],
    ["可是", "kě shì", "however", "tetapi / sebaliknya"],
    ["他拿", "tā ná", "he holding", "dia punya yang memegang"],
    ["菜刀的", "cài dào de", "cleaver's", "pisau dapur punya"],
    ["手", "shǒu", "hand", "tangan"],
    ["抽搐", "chōu chù", "twitching / convulsing", "mula tersentak-sentak / kejang saraf"],
    ["起来", "qǐ lái", "up", "mula"],
    ["，", "", "", ""],
    ["剧烈地", "jù liè de", "violently / intensely", "dengan tersangat hebat geger"],
    ["抖动", "dǒu dòng", "shaking / trembling", "menggeletar / gementar kencang"],
    ["起来", "qǐ lái", "up", "semula"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["哐啷", "kuāng lāng", "clatter / clang (sound marker)", "bunyi 'klang' besi tumpah"],
    ["”", "", "", ""],
    ["一声", "yì shēng", "a sound of", "satu kali berbunyi"],
    ["，", "", "", ""],
    ["菜刀", "cài dào", "the cleaver", "pisau pemotong daging itu"],
    ["落在", "luò zài", "fell on", "terjatuh tumpah di atas"],
    ["地上", "dì shàng", "ground", "tanah lantai"],
    ["，", "", "", ""],
    ["像", "xiàng", "resembles", "bagaikan / seolah-olah mirip"],
    ["一条", "yì tiáo", "one (snake marker)", "seekor"],
    ["僵死的", "jiāng sǐ de", "frozen dead", "ular kaku yang mati keras"],
    ["蛇", "shé", "snake", "ular"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 21 段
    ["壮汉", "zhuàng hàn", "The burly man", "Lelaki sasa itu"],
    ["捧着脸", "pěng zhe liǎn", "cupping his face with hands", "menekup mukanya dengan kedua-dua belah tangan"],
    ["蹲下来", "dūn xià lái", "squatted down", "lalu mencangkung turun"],
    ["，", "", "", ""],
    ["忽然", "tū rán", "suddenly / all of a sudden", "tiba-tiba sahaja seketika"],
    ["放声痛哭", "fàng shēng tòng kū", "burst into loud weeping", "melepaskan tangisan meratap tersangat sedih"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 22 段
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["依然", "yī rán", "still / as before", "tetap masih kekal"],
    ["站立着", "zhàn lì zhe", "standing upright", "berdiri tegak"],
    ["，", "", "", ""],
    ["午后的", "wǔ hòu de", "afternoon's", "petang hari punya"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["明亮亮地", "míng liàng liàng de", "brightly", "dengan terang-benderang"],
    ["照在", "zhào zài", "shone on", "menyinari di atas"],
    ["老人", "lǎo rén", "old man", "orang tua itu punya"],
    ["身上", "shēn shàng", "body", "badan"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["像", "xiàng", "resembles / like", "bagaikan / seolah-olah mirip"],
    ["巍然挺立的", "wēi rán tǐng lì de", "towering and standing upright", "sebatang pokok yang berdiri megah gagah"],
    ["一棵松", "yì kē sōng", "a pine tree", "pohon pain"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处 (完美对齐正文规范)
    ["（", "", "", ""],
    ["祝勇", "zhù yǒng", "Zhu Yong (Author)", "Zhu Yong (Penulis)"],
    ["《", "", "", ""],
    ["午后的", "wǔ hòu de", "Afternoon's", "Kisah"],
    ["故事", "gù shi", "Story", "Petang"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
